# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/alu_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/control_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/new/dmem.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/forward_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/hazard_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/new/imem.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/imm1_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/imm2_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/mux1_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/mux2_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/mux3.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/pcounter_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/reg_ex_mem.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/reg_id_ex.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/reg_if_id.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/reg_mem_wb.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/regfile_pi.sv
  C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.srcs/sources_1/imports/RISCV/riscv_pi.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_pi -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_pi.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_pi_utilization_synth.rpt -pb riscv_pi_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
