webtalk_init -webtalk_dir C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 23 12:33:07 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6d29b02e-4966-4812-88c2-cff91fc5f23d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b595671580c74984aa60539da8ab5d52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "83" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 3 3200G with Radeon Vega Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "10.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6944_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2593987548 -regid "" -xml C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Brian/Desktop/proyectoarqui1/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_riscv_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
